env_name: HalfCheetah-v4
env_task: ""
env_library: gym
async_collection: 1
record_video: 0
normalize_rewards_online: 1
normalize_rewards_online_scale: 5
frame_skip: 1
frames_per_batch: 1000
optim_steps_per_batch: 1000
total_frames: 1000000
prb: 1
ou_exploration: 1
multi_step: 1
init_random_frames: 5000
activation: elu
gSDE: 0
from_pixels: 0
#collector_devices: [cuda:1,cuda:1,cuda:1,cuda:1]
collector_devices: [cpu,cpu]
env_per_collector: 1
num_workers: 2
value_network_update_interval: 200
record_interval: 1000
max_frames_per_traj: 1000
annealing_frames: 1000000
init_env_steps: 1000
record_frames: 1000
loss_function: smooth_l1
batch_transform: 1
buffer_prefetch: 64
norm_stats: 1
