env_name: cheetah
env_task: run
env_library: dm-control
async_collection: 0
record_video: 1
normalize_rewards_online: 1
normalize_rewards_online_scale: 5
frame_skip: 1
frames_per_batch: 1000
optim_steps_per_batch: 10
batch_size: 256
total_frames: 5000000
world_model_lr: 6e-4
lr: 8e-5
from_pixels: 1
#collector_devices: [cuda:1]
collector_devices: [cpu]
env_per_collector: 4
num_workers: 4
lr_scheduler: ""
record_interval: 100
max_frames_per_traj: -1
weight_decay: 0.0
init_env_steps: 10000
record_frames: 50000
loss_function: smooth_l1
batch_transform: 1
