env_name: cheetah
env_task: run
env_library: dm_control
catframes: 1
async_collection: 1
record_video: 0
frame_skip: 2
frames_per_batch: 400
optim_steps_per_batch: 100
batch_size: 50
total_frames: 5000000
world_model_lr: 6e-4
actor_value_lr: 8e-5
from_pixels: True
# collector_devices: [cuda:1]
collector_devices: [cpu]
env_per_collector: 4
num_workers: 4
record_interval: 100
max_frames_per_traj: -1
init_env_steps: 1000 #50000
record_frames: 50000
batch_transform: 1
state_dim: 20
rssm_hidden_dim: 200
grad_clip: 100
grayscale: False
image_size : 64
